name: Deploy API
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build:cli
      - run: npm run link
      - name: Clone and validate all tempaltes
        run: myst-templates validate tex.yml
      - run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}
